rm -rf Elliptic/online*
rm -rf Elliptic/basis
rm -rf Elliptic/cache
rm -rf Elliptic/error_analysis
rm -rf Elliptic/post_processing
rm -rf Elliptic/reduced_operators
rm -rf Elliptic/snapshots
rm -rf Elliptic/speedup_analysis
rm -rf Elliptic/testing_set
rm -rf Elliptic/deim
rm -rf Elliptic/eim
